Machete.Web/Controllers/WorkerSigninController.cs
#region COPYRIGHT
// File:     WorkerSigninController.cs
// Author:   Savage Learning, LLC.
// Created:  2012/06/17 
// License:  GPL v3
// Project:  Machete.Web
// Contact:  savagelearning
// 
// Copyright 2011 Savage Learning, LLC., all rights reserved.
// 
// This source file is free software, under either the GPL v3 license or a
// BSD style license, as supplied with this software.
// 
// This source file is distributed in the hope that it will be useful, but 
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
// or FITNESS FOR A PARTICULAR PURPOSE. See the license files for details.
//  
// For details please refer to: 
// http://www.savagelearning.com/ 
//    or
// http://www.github.com/jcii/machete/
// 
#endregion

using System;
using System.Globalization;
using System.Linq;
using AutoMapper;
using Machete.Domain;
using Machete.Service;
using Machete.Service.DTO;
using Machete.Web.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Machete.Web.Controllers
{
    [ElmahHandleError]
    public class WorkerSigninController : MacheteController
    {
        private readonly IWorkerSigninService serv;
        private readonly IMapper map;
        private readonly IDefaults def;
        private CultureInfo CI;        
        public WorkerSigninController(IWorkerSigninService workerSigninService, 
            IDefaults def,
            IMapper map)
        {
            serv = workerSigninService;
            this.map = map;
            this.def = def;
        }

        protected override void Initialize(ActionContext requestContext)
        {
            base.Initialize(requestContext);
            CI = Session["Culture"];
        }
        //
        // GET: /WorkerSignin/
        // Initial page creation
        [Authorize(Roles = "Manager, Administrator, Check-in")]
        public ActionResult Index()
        {        
            return View();
        }
        //
        // POST: /WorkerSignin/Index -- records a signin
        [HttpPost, UserNameFilter]
        [Authorize(Roles = "Manager, Administrator, Check-in")]
        public ActionResult Index(int dwccardnum, DateTime dateforsignin, string userName)
        {
            var wsi = serv.CreateSignin(dwccardnum, dateforsignin, userName);
            var result = map.Map<WorkerSignin, ViewModel.WorkerSignin>(wsi);
            return Json(result);

        }
        /// <summary>
        /// This method invokes IWorkerSigninService.moveDown,
        /// which moves a worker down in numerical order in the daily 
        /// ('lottery') list,
        /// and moves the proceeding (next) set member into their spot.
        /// </summary>
        /// <param name="id">The Worker ID of the person to be moved down.</param>
        /// <param name="userName">The username of the person making the request.</param>
        /// <returns>Json (bool jobSuccess, string status)</returns>
        [UserNameFilter]
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult moveDown(int id, string userName)
        {
            serv.moveDown(id, userName);
            return Json(new
            {
                jobSuccess = true,
                status = "OK", 
                workerID = id
            });
        }

        /// <summary>
        /// This method invokes IWorkerSigninService.moveUp,
        /// which moves a worker up in numerical order in the 
        /// daily ('lottery') list,
        /// and moves the preceeding set member into their spot.
        /// </summary>
        /// <param name="id">The Worker ID of the person to be moved down.</param>
        /// <param name="userName">The username of the person making the request.</param>
        /// <returns>Json (bool jobSuccess, string status)</returns>
        [UserNameFilter]
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult moveUp(int id, string userName)
        {
            serv.moveUp(id, userName);
            return Json(new
            {
                jobSuccess = true,
                status = "OK",
                workerID = id
            });
        }

        // GET: /WorkerSignin/Delete/5
       /// <summary>
       /// This method deletes a signin from the master Worker Signins list for the day.
       /// </summary>
       /// <param name="id">The Worker ID of the worker.</param>
       /// <param name="userName">The user performing the action.</param>
       /// <returns>Json (bool jobSuccess, string status, int deletedID)</returns>
        [UserNameFilter]
        [Authorize(Roles = "Administrator, Manager, Check-in")]
        public JsonResult Delete(int id, string userName)
        {
            var record = serv.Get(id);
            if (record.WorkAssignmentID != null)
            {
                return Json(new
                    {
                        jobSuccess = false,
                        rtnMessage = "You cannot delete a signin that has been associated with an Assignment. Disassociate the sigin with the assignment first."
                    });
            }

            serv.Delete(id, userName);            
            return Json(new
            {
                jobSuccess = true,
                status = "OK",
                deletedID = id
            });
        }

        [Authorize(Roles = "Administrator, Manager, Check-in")]
        public ActionResult AjaxHandler(jQueryDataTableParam param)
        {
            var vo = map.Map<jQueryDataTableParam, viewOptions>(param);
            vo.CI = CI;
            dataTableResult<WorkerSigninList> was = serv.GetIndexView(vo);
            var result = was.query
                .Select(e => map.Map<WorkerSigninList, ViewModel.WorkerSigninList>(e))
                .AsEnumerable();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = was.totalCount,
                iTotalDisplayRecords = was.filteredCount,
                aaData = result
            });
        }
    }
}

Machete.Web/Views/WorkerSignin/Index.cshtml
@model Machete.Web.ViewModel.WorkerSignin
@using Machete.Web.Resources
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Localization

<link href="@Url.Content("~/Content/print.css")" rel="stylesheet" type="text/css" media="print" />
@{
    ViewBag.Title = WorkerSignins.indextitle;

    var httpContext = ViewContext.HttpContext;
    var currentCulture = httpContext.Features.Get<IRequestCultureFeature>().RequestCulture.UICulture;
    var currentUrl = UriHelper.BuildRelative(httpContext.Request.PathBase, httpContext.Request.Path, httpContext.Request.QueryString);
}

<div id="container" class="wsi-content">
    <div id="signinData" class="signinColumn" style="float: left;">
        <div class="print_off">
        @using (Html.BeginForm("Index", "WorkerSignin", FormMethod.Post, new { @id = "signinForm" }))
        {
            @Html.ValidationSummary(true)
            <div class="tb-table">
                <div class="tb-row">
                    <div class="tb-label">
                        @Html.LabelFor(model => model.dwccardnum)
                    </div>
                    <div class="tb-field">
                        @Html.TextBox("dwccardnum", "", new { style = "width: 100px;", @class="wsi-dwccardnum" })
                        @Html.ValidationMessageFor(model => model.dwccardnum)
                    </div>
                    <div class="tb-field">
                        @Html.TextBox("dateforsignin",
                            Html.Encode(String.Format("{0:mm/dd/yy}", DateTime.Today.ToShortDateString())),
                            new { @class = "ui-datepicker wsi-datepicker", style = "width: 100px;" })
                        @Html.ValidationMessageFor(model => model.dateforsignin)
                    </div>
                    <div class="tb-field">            
                        <input type="submit" value="@WorkerSignins.indexsubmit" class="formButton report-button" />
                    </div>
                </div>
            </div>
        }
        </div>
        <div id="signinTable">
            <table id="wsiTable" class="display">
                <thead>
                    <tr>
                        <th class="print_off"></th>
                        <th>@Worker.dwccardnum</th>
                        <th class="print_off">@WorkerSignins.memberexpiration</th>
                        <th class="print_off">@WorkerSignins.status</th>
                        <th>@WorkerSignins.firstname</th>
                        <th>@WorkerSignins.lastname</th>
                        <th class="print_off">@WorkerSignins.datesignin</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
    <div id="signinImage" class="mui-signin-imagebox print_off">
        <img id="wsiImage" src="/Content/images/NO-IMAGE-AVAILABLE.jpg" alt="" class="wsi-image" />
    </div>
</div>
<div id="signin-red-dialog">
    @WorkerSignins.redmessage
    <img id="wsiRedImage" src="" alt="" style="width: 200px"/>
</div>
<div id ="signin-unknown">
    @WorkerSignins.unknownmessage
</div>

<script type="text/javascript">
    $().ready(function () {
        var blankImage = "/Content/images/NO-IMAGE-AVAILABLE.jpg";
        var currentUrl = window.location.href;
        var True = true;
        var False = false;
        //
        //
        $('.ui-datepicker').datepicker({
            dateFormat: 'mm/dd/yy',
            onClose: function () { $('#wsiTable').dataTable().fnDraw(); }
        });
        //
        //
        $('#dwccardnum').focus();
        $('#signin-red-dialog').hide();
        $('#signin-unknown').hide();
        $('.confirm_delete').live('click', function (e) {
            e.preventDefault;
            //TODO: event is posting and returning page, not JSON
            var action =  $(this).attr('href');
            $.alerts.okButton = "@WorkerSignins.deletesubmit";
            jConfirm('@WorkerSignins.deleteconfirmation',
                         '@WorkerSignins.deletetitle',
                         function (r) {
                             if (r == true) { 
                             $.post(action, null, function(data) {

                                 $('#wsiTable').dataTable().fnDraw();
                                 $('#wsiImage').attr('src', blankImage);
                                    if (!data.jobSuccess) {
                                        alert(data.rtnMessage);                                        
                                    } 
                             });
                             }
                             $('#dwccardnum').focus();
                         });
            return false;
        });
        //
        //
        $('#wsiTable').dataTable({
            "sScrollY": "315px",
            "bPaginate": false,
            "bLengthChange": true,
            "bAutoWidth": false,
            "bServerSide": true,
            "bInfo": true,
            "bSort": true,
            "bFilter": true,
            "sAjaxSource": "/WorkerSignin/AjaxHandler",
            "oLanguage": datatable_lang_@(currentCulture.TwoLetterISOLanguageName),
            "bProcessing": true,
            "iDisplayLength": 15,
            //"aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "@WorkerSignins.allrecords"]],
            "aoColumns": [
                {mDataProp: "recordid", sClass: "print_off"},
                {mDataProp: "dwccardnum"},
                {mDataProp: "expirationDate", sClass: "print_off"},
                {mDataProp: "memberStatus", sClass: "print_off"},
                {mDataProp: "firstname1"},
                {mDataProp: "lastname1"},
                {mDataProp: "dateforsigninstring", sClass: "print_off"}
            ],
            "fnServerData": function ( sSource, aoData, fnCallback ) {
			    /* Add some extra data to the sender */
			    aoData.push( { "name": "todaysdate", "value": $('#dateforsignin').val() } );
			    $.getJSON( sSource, aoData, function (json) { 
				    /* Do whatever additional processing you want on the callback, then tell DataTables */
				    fnCallback(json)
			    } );
		    },
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                $(nRow).attr('ID', "wsiRec" +aData['recordid']);
                $(nRow).find('td:first-child').html('<a class="confirm_delete" href="/WorkerSignin/delete/'+aData['recordid']+'">Delete</a>');
                if (aData['imageID']) {
                    $(nRow).attr('imageRef', "/Image/GetImage/" + aData['imageID']);
                } else {
                    $(nRow).attr('imageRef', blankImage);
                }
                $(nRow).addClass('statusBlue');
                if (aData['memberInactive'] || aData['memberExpired']) { 
                    $(nRow).removeClass('statusBlue');
                    $(nRow).addClass('statusYellow');
                } 
                if (aData['memberSanctioned'] || aData['memberExpelled']) {
                    $(nRow).removeClass('statusBlue');
                    $(nRow).removeClass('statusYellow');
                    $(nRow).addClass('statusRed');
                } 
                return nRow;
            }
        });
        //
        //
        $('.dataTables_length, .dataTables_filter, .dataTables_info, #wsiTable_previous, #wsiTable_next').addClass('print_off');
        $('#wsiTable tbody').bind('dblclick', function(e) {
            console.log('d-click');
            var $node = $(e.target.parentNode);
            $('#wsiImage').attr('src', $node.attr('imageRef'));
        });
        //
        //
        $('#signinForm').submit(function(e) {
            var form = this;
            e.preventDefault();
            if ($(form).valid()) {
                $.post($(this).attr("action"), $(this).serialize(), 
                    function(data) {
                        $('#dwccardnum').val(null); // clear cardnum field
                        $('#wsiImage').attr('src', data.imageRef); //reload image
                        $('#wsiTable').dataTable().fnDraw(); //reload datatable

    
                        if (data.memberSanctioned || data.memberExpelled) {
                            $("#wsiRedImage").attr('src', data.imageRef);
                            $('#signin-red-dialog').dialog({ 
                                modal: true,
                                buttons: {
				                    Ok: function() {
					                    $( this ).dialog( "close" );
				                    }
			                    },
                                title: "@(WorkerSignins.redmessagetitle)",
                                close: function(event, ui) { $('#dwccardnum').focus(); }
                                 });
                        }
                        if (data.jobSuccess == false) {
                        $('#signin-unknown').dialog({ 
                                modal: true,
                                buttons: {
				                    Ok: function() {
					                    $( this ).dialog( "close" );
				                    }
			                    },

                                title: "@(WorkerSignins.unknownmessagetitle)",
                                close: function(event, ui) { $('#dwccardnum').focus(); }
                                 });
                        }
                        $('#dwccardnum').focus();
                    });
            }    
        });
    });
</script>