Machete.Web/Controllers/WorkerController.cs
#region COPYRIGHT
// File:     WorkerController.cs
// Author:   Savage Learning, LLC.
// Created:  2012/06/17 
// License:  GPL v3
// Project:  Machete.Web
// Contact:  savagelearning
// 
// Copyright 2011 Savage Learning, LLC., all rights reserved.
// 
// This source file is free software, under either the GPL v3 license or a
// BSD style license, as supplied with this software.
// 
// This source file is distributed in the hope that it will be useful, but 
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
// or FITNESS FOR A PARTICULAR PURPOSE. See the license files for details.
//  
// For details please refer to: 
// http://www.savagelearning.com/ 
//    or
// http://www.github.com/jcii/machete/
// 
#endregion

using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Machete.Domain;
using Machete.Service;
using Machete.Service.DTO;
using Machete.Web.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Machete.Web.Controllers
{
    [ElmahHandleError]
    public class WorkerController : MacheteController
    {
        private readonly IWorkerService serv;
        private readonly IImageService imageServ;
        private readonly IMapper map;
        private readonly IDefaults def;
        CultureInfo CI;

        public WorkerController(IWorkerService workerService, 
                                IPersonService personService,
                                IImageService  imageServ,
            IDefaults def,
            IMapper map)
        {
            serv = workerService;
            this.imageServ = imageServ;
            this.map = map;
            this.def = def;
        }
        protected override void Initialize(ActionContext requestContext)
        {
            base.Initialize(requestContext);
            CI = Session["Culture"];
            // TODO this needs to be scheduled elsewhere
            //serv.ExpireMembers();
            //serv.ReactivateMembers();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Manager, Administrator, Teacher, PhoneDesk")]
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="param"></param>
        /// <returns></returns>
        [Authorize(Roles = "Administrator, Manager, Teacher, PhoneDesk")]
        public ActionResult AjaxHandler(jQueryDataTableParam param)
        {
            var vo = map.Map<jQueryDataTableParam, viewOptions>(param);
            vo.CI = CI;
            dataTableResult<WorkerList> list = serv.GetIndexView(vo);
            var result = list.query
            .Select(
                e => map.Map<WorkerList, ViewModel.WorkerList>(e)
            ).AsEnumerable();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = list.totalCount,
                iTotalDisplayRecords = list.filteredCount,
                aaData = result
            });
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="wkr"></param>
        /// <returns></returns>
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [Authorize(Roles = "PhoneDesk, Manager, Teacher, Administrator")] 
        public ActionResult Create(int ID)
        {
            // TODO handle exception of next worker number
            var nextnum = serv.GetNextWorkerNum();
            var w = map.Map<Worker, ViewModel.Worker>(new Worker {
                ID = ID,
                dwccardnum = nextnum
            });
            w.def = def;
            return PartialView("Create", w);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="worker"></param>
        /// <param name="userName"></param>
        /// <param name="imagefile"></param>
        /// <returns></returns>
        [HttpPost, UserNameFilter]
        [Authorize(Roles = "PhoneDesk, Manager, Teacher, Administrator")]
        public async Task<ActionResult> Create(Worker worker, string userName, IFormFile imagefile)
        {
            if (await TryUpdateModelAsync(worker)) {
                if (imagefile != null) await updateImage(worker, imagefile);
                Worker newWorker = serv.Create(worker, userName);
                var result = map.Map<Worker, ViewModel.Worker>(newWorker);
                return Json(new {
                    sNewRef = result.tabref,
                    sNewLabel = result.tablabel,
                    iNewID = result.ID,
                    jobSuccess = true
                });
            } else {
                return Json(new {jobSuccess = "false"});
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "PhoneDesk, Manager, Teacher, Administrator")] 
        public ActionResult Edit(int id)
        {
            Worker w = serv.Get(id);
            var m = map.Map<Worker, ViewModel.Worker>(w);
            m.def = def;
            return PartialView(m);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="_model"></param>
        /// <param name="userName"></param>
        /// <param name="imagefile"></param>
        /// <returns></returns>
        [HttpPost, UserNameFilter]
        [Authorize(Roles = "PhoneDesk, Manager, Teacher, Administrator")]
        public async Task<ActionResult> Edit(int id, Worker _model, string userName, IFormFile imagefile)
        {
            Worker worker = serv.Get(id);
            if (await TryUpdateModelAsync(worker)) {
            
            if (imagefile != null) await updateImage(worker, imagefile);                
            serv.Save(worker, userName);
            return Json(new
            {
                jobSuccess = true
            });
            } else { return Json(new { jobSuccess = false }); }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost, UserNameFilter]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, string user)
        {            
            serv.Delete(id, user);

            return Json(new
            {
                status = "OK",
                deletedID = id
            });
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="worker"></param>
        /// <param name="imageFile"></param>
        [Authorize(Roles = "PhoneDesk, Manager, Teacher, Administrator")]
        private async Task updateImage(Worker worker, IFormFile imageFile)
        {
            var userIdentity = new ClaimsIdentity("Cookies");
            if (worker == null) throw new MacheteNullObjectException("updateImage called with null worker");
            if (imageFile == null) throw new MacheteNullObjectException("updateImage called with null imagefile");
            if (worker.ImageID != null)
            {
                var image = imageServ.Get((int)worker.ImageID);
                image.ImageMimeType = imageFile.ContentType;
                image.parenttable = "Workers";
                image.filename = imageFile.FileName;
                image.recordkey = worker.ID.ToString();
                image.ImageData = new byte[imageFile.Length];

                using (var memoryStream = new MemoryStream()) {
                    await imageFile.CopyToAsync(memoryStream);
                    image.ImageData = memoryStream.ToArray();
                }

                imageServ.Save(image, userIdentity.Name);
            }
            else
            {
                var image = new Image();
                image.ImageMimeType = imageFile.ContentType;
                image.parenttable = "Workers";
                image.recordkey = worker.ID.ToString();
                image.ImageData = new byte[imageFile.Length];

                using (var memoryStream = new MemoryStream()) {
                    await imageFile.CopyToAsync(memoryStream);
                    image.ImageData = memoryStream.ToArray();
                }
                
                Image newImage = imageServ.Create(image, userIdentity.Name);
                worker.ImageID = newImage.ID;
            }
        }
    }
}

Machete.Web/Views/Worker/Create.cshtml
@model Machete.Web.ViewModel.Worker
@using Machete.Web.Resources
@{  
    string recType = "worker";
    string idPrefix = recType + Model.ID + "-";
}
@using (Html.BeginForm("Create", "Worker", FormMethod.Post, 
    new { @id = "workerCreateForm", enctype = "multipart/form-data" }))
{
    <div class="mui-button-row">
        <input type="submit" id="createWorkerBtn"  class="formButton saveBtn" value="@Workers.createsubmit" tabindex="9"/>
        <p class="validation-summary-errors">@ViewBag.OrganizeMe</p>
    </div>
    @Html.ValidationSummary(true)
    @Html.EditorForModel()
}
<script type="text/javascript">
    $(document).ready(function () {
        $('.formButton').button();
        var workerCreateForm = $('#workerCreateForm');
        $.validator.unobtrusive.parseDynamicContent(workerCreateForm);
        //
        // submit edit
        workerCreateForm.mUI('tabFormSubmit', {
            recType: "@(recType)", //for add_rectab
            create: false, // worker doesn't create a new tab
            selectTab: 0,
            formLevel: 1,
            postProcess: function () {
                var oTabs = $(workerCreateForm).closest('.ui-tabs');
                //$(oTabs).tabs("select", 0);
                $(oTabs).tabs("url", 1, "/Worker/Edit/@(Model.ID)");
                var createtab = $(oTabs).children('.ui-tabs-nav').find('a').get('1');
                $(createtab).text("@(Persons.workerinfo)");
            }
        });
        workerCreateForm.mUI('formDetectChanges', {
            recType: "@(recType)",
            formLevel: 1,
            changeConfirm: "@(Machete.Web.Resources.Shared.changeConfirm)",
            changeTitle: "@(Machete.Web.Resources.Shared.changeTitle)"
        });
//        workerCreateForm.submit(function (e) {
//            e.preventDefault();
//            if ($('#workerCreateForm').valid()) {

//                $.post($(this).attr("action"), $(this).serialize(),
//                    function (data) {
//                    }
//                );
//                var oTabs = $(e.target).closest('.ui-tabs');
//                $(oTabs).tabs("select", 0);
//                $(oTabs).tabs("url", 1, "/Worker/Edit/@(Model.ID)");
//                var createtab = $(oTabs).children('.ui-tabs-nav').find('a').get('1');
//                $(createtab).text("@(Persons.workerinfo)");
//            }
//            //TODO: javascript...need to deal with ajax error
//        });
    });
</script>

Machete.Web/Views/Worker/Edit.cshtml
@model Machete.Web.ViewModel.Worker
@using Machete.Web.Resources
@using Machete.Web.Helpers

@{
    string recType = "worker";
    //string idPrefix = recType + "-";
    string parentPrefix = "person" + Model.ID + "-";
    string idPrefix = recType + Model.ID + "-";
}
@using (Html.BeginForm("Edit", "Worker", FormMethod.Post,
                    new { @class = "edittab-form EditPost", 
                          @id = "workerEditTab-" + Model.ID, 
                          enctype = "multipart/form-data" }))
{
    @*<input type="button" value="@Workers.printlink" class="formButton" id="viewWorker-@(Model.ID)" />*@
    <input type="submit" value="@Workers.editsubmit" class="formButton saveBtn" id="@(idPrefix)SaveButton"/>
    
    if (Html.IsInRole(new[] { "Administrator", "Manager" }))
    {
        <input id="deleteWorkerButton-@(Model.ID)" type="button" value="@Workers.deletesubmit" 
                class="formButton deleteButton" />
    }
    <br />  
    @Html.ValidationSummary(true)
    @Html.EditorForModel()

}

@if (Html.IsInRole(new[] { "Administrator", "Manager" }))
{
    using (Html.BeginForm("Delete", "Worker", FormMethod.Post,
                            new { @class = "edittab-form DeletePost", @id = "deleteWorker-" + Model.ID }))
    {
        @Html.HiddenFor(model => model.ID);
    }
}

@await Html.PartialAsync("WorkerWAIndex", Model)
<script type="text/javascript">
    $(document).ready(function () {
        var personPartsTab = $('#@(parentPrefix)personPartsTabs');
        $('.formButton').button();
        //TODO: Tab order $('#contactName').focus();
        $.validator.unobtrusive.parseDynamicContent($('#workerEditTab-@Model.ID'));
        //
        // open work order view for printing
        // TODO: remove worker print
        //$('#viewWorker-@(Model.ID)').click(function () {
        //    printwindow = window.open('/Worker/View/@(Model.ID)');
            //printwindow.print();
        //});
        //
        // Confirm delete event
        $('#deleteWorkerButton-@Model.ID').mUI('formClickDelete', {
            ok: "@Workers.deletesubmit",
            confirm: '@Workers.deleteconfirmation',
            title: '@Workers.deletetitle',
            form: $('#deleteWorker-@(Model.ID)'),
            altClose: $('#personGeneralTab'),
            postDelete: function () {
                personPartsTab.tabs("url", 1, "/Worker/Create?ID=@(Model.ID)");
                var createtab = $(personPartsTab).children('.ui-tabs-nav').find('a').get('1');
                $(createtab).text("@(Persons.createworker)");
            }
        });
        //
        // submit edit
        $('#workerEditTab-@Model.ID').mUI('tabFormSubmit', {
            create: false,
            selectTab: 0,
            formLevel: 1
        });
        // 
        //
        $('#workerEditTab-@Model.ID').mUI('formDetectChanges', {
            recType: "@(recType)",
            formLevel: 1,
            changeConfirm: "@(Machete.Web.Resources.Shared.changeConfirm)",
            changeTitle: "@(Machete.Web.Resources.Shared.changeTitle)"
        });
    });
</script>

Machete.Web/Views/Worker/Index.cshtml
@using Machete.Web.Helpers
@using Machete.Web.Resources
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Localization

@{
    ViewBag.Title = Workers.indextitle;

    var httpContext = ViewContext.HttpContext;
    var currentCulture = httpContext.Features.Get<IRequestCultureFeature>().RequestCulture.UICulture;
    var currentUrl = UriHelper.BuildRelative(httpContext.Request.PathBase, httpContext.Request.Path, httpContext.Request.QueryString);
}
<div id="workerTabs">
    <ul>
        <li><a href="#workerList" id="workerListTab" class="ListTab">@Workers.listlink</a> </li>
        @*<li><a href="/Worker/Create" id="workerCreateTab" class="CreateTab">@Workers.createlink</a></li>*@
    </ul>
    <div id="workerList">
        <table id="workerTable" class="display">
            <thead>
                <tr>
                    <th>EDITREF</th>
                    <th>LABEL</th>
                    <th>ID</th>
                    <th>@Worker.dwccardnum</th>
                    <th>@Worker.memberStatus</th>
                    <th>@Person.firstname1</th>
                    <th>@Person.firstname2</th>
                    <th>@Person.lastname1</th>
                    <th>@Person.lastname2</th>
                    <th>@Worker.memberexpirationdate</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        jqrfyTable({
        table: $('#workerTable'),
        tab: $('#workerTabs'),
        options: {
            "bPaginate": true,
            "bLengthChange": true,
            "aaSorting": [[9, 'desc']],
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": false,
            "bServerSide": true,
            "sAjaxSource": "Worker/AjaxHandler",
            "oLanguage": datatable_lang_@(currentCulture.TwoLetterISOLanguageName),
            "bProcessing": true,
            "aoColumns": [
                { "mDataProp": "tabref","bSearchable": false, "bSortable": false, "bVisible": false },
                { "mDataProp": "tablabel","bSearchable": false, "bSortable": false, "bVisible": false },
                { "mDataProp": "WID","bSearchable": false, "bSortable": false, "bVisible": false },
                { "mDataProp": "dwccardnum" },
                { "mDataProp": "memberStatus" },
                { "mDataProp": "firstname1" },
                { "mDataProp": "firstname2" },
                { "mDataProp": "lastname1" },
                { "mDataProp": "lastname2" },
                { "mDataProp": "memberexpirationdate" }
            ],
            // callback populates html attr with row data from JSON
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                $(nRow).attr('recordid', aData['WID']);
                switch (aData['memberStatusID'])
                {
                    case "@(Machete.Domain.Worker.iActive)": $(nRow).addClass('statusBlue'); break;
                    case "@(Machete.Domain.Worker.iInactive)": $(nRow).addClass('statusYellow'); break;
                    case "@(Machete.Domain.Worker.iExpired)": $(nRow).addClass('statusYellow'); break;
                    case "@(Machete.Domain.Worker.iSanctioned)": $(nRow).addClass('statusRed'); break;
                    case "@(Machete.Domain.Worker.iExpelled)": $(nRow).addClass('statusRed'); break;
                    default: $(nRow).addClass('statusBlue');
                }
                return nRow;
            }
        },
        dblClickEvent: null,
        tabLabel: null
        });
        $('#workerTabs').mUI('createTabs', {
            prefix: "ui-tabs-worker-",
            formLevel: 1,
            changeConfirm: "@Shared.changeConfirm",
            changeTitle:   "@Shared.changeTitle"
        });
    });
</script>