Machete.Web/Controllers/EmployerController.cs
#region COPYRIGHT
// File:     EmployerController.cs
// Author:   Savage Learning, LLC.
// Created:  2012/06/17 
// License:  GPL v3
// Project:  Machete.Web
// Contact:  savagelearning
// 
// Copyright 2011 Savage Learning, LLC., all rights reserved.
// 
// This source file is free software, under either the GPL v3 license or a
// BSD style license, as supplied with this software.
// 
// This source file is distributed in the hope that it will be useful, but 
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
// or FITNESS FOR A PARTICULAR PURPOSE. See the license files for details.
//  
// For details please refer to: 
// http://www.savagelearning.com/ 
//    or
// http://www.github.com/jcii/machete/
// 
#endregion

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Machete.Domain;
using Machete.Service;
using Machete.Service.DTO;
using Machete.Web.Helpers;
using Machete.Web.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Employer = Machete.Domain.Employer;

namespace Machete.Web.Controllers
{

    [ElmahHandleError]
    public class EmployerController : MacheteController
    {
        private readonly IEmployerService serv;
        private readonly IMapper map;
        private readonly IDefaults def;
        private CultureInfo CI;

        public EmployerController(
            IEmployerService employerService, 
            IDefaults def,
            IMapper map
        ) {
            serv = employerService;
            this.map = map;
            this.def = def;
        }
        protected override void Initialize(ActionContext requestContext)
        {
            base.Initialize(requestContext);
            CI = Session["Culture"];
            ViewBag.idPrefix = "employer";
        }

        // GET: /Employer/Index
        [Authorize(Roles = "Administrator, Manager, PhoneDesk")]
        public ActionResult Index()
        {
            return View();
        }
        
        // GET: /Employer/AjaxHandler
        [Authorize(Roles = "Administrator, Manager, PhoneDesk")]
        public JsonResult AjaxHandler(jQueryDataTableParam param)
        {
            dataTableResult<EmployersList> list;

            try {
                var vo = map.Map<jQueryDataTableParam, viewOptions>(param);
                vo.CI = CI;
                list = serv.GetIndexView(vo);
            }
            catch (Exception ex) {
                throw ex; // TODO Chaim plz
            }
            //return what's left to datatables
            var result = list.query
                .Select(e => map.Map<EmployersList, EmployerList>(e))
                .AsEnumerable();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = list.totalCount,
                iTotalDisplayRecords = list.filteredCount,
                aaData = result
            });
        }

        // GET: /Employer/Create
        [Authorize(Roles = "Administrator, Manager, PhoneDesk")]
        public ActionResult Create()
        {
            var model = map.Map<Employer, ViewModel.Employer>(new Employer
            {
                active = true,
                blogparticipate = false,
                referredby = def.getDefaultID(LCategory.emplrreference)
            });
            model.def = def;
            return PartialView("Create", model);
        }

        // POST: /Employer/Create
        [HttpPost, UserNameFilter]
        [Authorize(Roles = "Administrator, Manager, PhoneDesk")]
        public async Task<JsonResult> Create(Employer employer, string userName)
        {
            if (await TryUpdateModelAsync(employer)) {
                var result = map.Map<Employer, ViewModel.Employer>(serv.Create(employer, userName));
                return Json(new {
                    sNewRef = result.tabref,
                    sNewLabel = result.tablabel,
                    iNewID = result.ID,
                    jobSuccess = true
                });
            } else {
                return Json(new { jobSuccess = false });
            }
        }

        /// <summary>
        /// GET: /Employer/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Administrator, Manager, PhoneDesk")]
        public ActionResult Edit(int id)
        {
            var e = serv.Get(id);
            var m = map.Map<Employer, ViewModel.Employer>(e);
            m.def = def;
            return PartialView("Edit", m);
        }

        /// <summary>
        /// POST: /Employer/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <param name="userName"></param>
        /// <returns></returns>
        [HttpPost, UserNameFilter]
        [Authorize(Roles = "Administrator, Manager, PhoneDesk")]
        public async Task<JsonResult> Edit(int id, string userName)
        {
            var employer = serv.Get(id);
            if (await TryUpdateModelAsync(employer)) {
                serv.Save(employer, userName);
                return Json(new { jobSuccess = true });
            } else {
                return Json(new { jobSuccess = false });
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="userName"></param>
        /// <returns></returns>
        [HttpPost, UserNameFilter]
        [Authorize(Roles = "Administrator")]
        public JsonResult Delete(int id, string userName)
        {
            serv.Delete(id, userName);

            return Json(new
            {
                status = "OK",
                jobSuccess = true,
                deletedID = id
            });
        }

        [Authorize(Roles = "Administrator, Manager, PhoneDesk")]
        public JsonResult GetDuplicates(string name, string address, string phone, string city, string zipcode)
        {
            var name1 = name;
            var address1 = address;
            var phone1 = phone;
            var city1 = city;
            var zipcode1 = zipcode;
            //Get all the records            
            var list = serv.GetAll();
            var employersFound = new List<Dictionary<string, string>>();
            
            name1 = name1.Replace(" ", "");
            address1 = address1.Replace(" ", "");
            phone1 = string.IsNullOrEmpty(phone1) ? "nonMatchingValue" : phone1;
            city1 = city1.Replace(" ","");
            zipcode1 = zipcode1.Replace(" ","");

            foreach (var employer in list)
            {
                var employerName = employer.name.Replace(" ", "");
                var employerAddress = employer.address1.Replace(" ", "");
                var employerPhone = string.IsNullOrEmpty(employer.phone) ? string.Empty : employer.phone;
                var employerCity = employer.city.Replace(" ","");
                var employerZipcode = employer.zipcode.Replace(" ","");

                //checking if person already exists in database
                var matchCount = 0;
                if (employerName.Equals(name1, StringComparison.CurrentCultureIgnoreCase)) matchCount++;
                if (employerAddress.Equals(address1, StringComparison.CurrentCultureIgnoreCase)) matchCount++;
                if (employerPhone.Equals(phone1, StringComparison.CurrentCultureIgnoreCase)) matchCount++;
                if (employerZipcode.Equals(zipcode1, StringComparison.CurrentCultureIgnoreCase)) matchCount++;
                if (employerCity.Equals(city1, StringComparison.CurrentCultureIgnoreCase)) matchCount++;


                if (matchCount < 3) continue;
                var employerFound = new Dictionary<string, string> {
                    { "Name", employer.name },
                    { "Address", employer.address1 },
                    { "Phone", employer.phone },
                    { "City", employer.city },
                    { "ZipCode", employer.zipcode },
                    { "ID", employer.ID.ToString() }
                };

                employersFound.Add(employerFound);
            }

            return Json(new {
                duplicates = employersFound
            });
        }
    }
}

Machete.Web/Views/Employer/Create.cshtml
@model Machete.Web.ViewModel.Employer

@using Machete.Web.Resources

@{  
    string recType = "employer";
    string idPrefix = recType + Model.ID + "-";
}

@using (Html.BeginForm("Create", "Employer", FormMethod.Post, 
                        new { id = "employerCreateForm" }))
{
    <div style="float: left;">
        <input type="button" onclick="FindEmployerDuplicate()" id="@(idPrefix)SaveBtn" class="formButton saveBtn" 
               value="@Employers.createsubmit" tabindex="9" />
        <input type="button" onclick="setFormData(true)" id="@(idPrefix)ClearBtn" class="formButton saveBtn"
               value="@Employers.createclear" tabindex="9" />
    </div>
     @Html.ValidationSummary(true)
     @Html.EditorForModel()
}

<div id="duplicatesDialog" title="@Shared.DuplicateEmployerTitle">
</div>

<script type="text/javascript">
    $(document).ready(function () {
        //setFormData is false, then the fields are kept (not cleared) on the Create New Employer form
        setFormData(false);
        var employerCreateForm = $("#employerCreateForm")
        $('.formButton').button();
        $.validator.unobtrusive.parseDynamicContent('#employerCreateForm');

        $('#employerName').focus();
        // Employer Create submit event
        
        employerCreateForm.mUI('tabFormSubmit', {
            recType: "@(recType)", //for add_rectab
            create: true,
            formLevel: 1
        });
        //
        // machete UI detect changes on forms in tabs   
        employerCreateForm.mUI('formDetectChanges', {
            recType: "@(recType)",
            formLevel: 1,
            changeConfirm: "@Shared.changeConfirm",
            changeTitle: "@Shared.changeTitle"
        });
    });

    function getClearValue(fieldName) {
        switch (fieldName) {
        case 'business':
        case 'returnCustomer':
        case 'onlineSource':
        case 'blogparticipate':
        case 'receiveUpdates':
            return "false";
        //break;
        case 'active':
            return "true";
        //break;
        default:
            return "";
        }
    }


    // function to restore typed-not saved fields on Create New Employer form when tabbing back from List of Employers
    function setFormData(clearForm) {

        var form = $('#employerCreateForm');
        var fieldChanged = false;
        var employerFormContent = JSON.parse(localStorage.getItem('employerCreateForm'));

        $.each(employerFormContent, function (i, field) {
            if (field.name == "ID") {
                return;
            }
            var fieldObj = $("#employer0-" + field.name);
            if (fieldObj != null && fieldObj.length > 0) {
                fieldObj.val(clearForm ? getClearValue(field.name) : field.value);
                if (fieldObj.val() != getClearValue(field.name)) {
                    fieldChanged = true;
                }
            }
        });

        // if any field had a change then it triggers save button to be highlighted again
        if (fieldChanged) {
            form.find('.saveBtn').addClass('highlightSave');
        }
        else {
            form.find('.saveBtn').removeClass('highlightSave');
        }

    }

    var duplicatesDialog = $("#duplicatesDialog").dialog({
        autoOpen: false,
        height: 400,
        width: 650,
        modal: true,
        closeOnEscape: false,
        buttons: {
            "Cancel": function () { $(this).dialog('close'); },
            "Save": {
                text: '@Employers.createsubmit',
                id: 'duplicateSaveBtn',
                click: function() {
                    $(this).dialog("close");
                    saveEmployer();
                }
            }

        }
    });

    function FindEmployerDuplicate() {
        var form = $('#employerCreateForm');
        if (form.valid()) {
            
            /* * * FOR DEBUGGING * * */
//            alert($('#employer0-name')[0].value);
//            alert($('#employer0-address1')[0].value);
//            alert($('#employer0-phone')[0].value);
//            alert($('#employer0-city')[0].value);
//            alert($('#employer0-zipcode')[0].value);
            $.ajax({
                url: "/Employer/GetDuplicates",
                data: {
                    name: $('#employer0-name')[0].value,
                    address: $('#employer0-address1')[0].value,
                    phone: $('#employer0-phone')[0].value,
                    city: $('#employer0-city')[0].value,
                    zipcode: $('#employer0-zipcode')[0].value
                },
                success: (result) => {
                    if (result.duplicates.length > 0) {
                        duplicatesDialog.dialog("open");
                        duplicatesDialog.html(CreateHtmlText(result.duplicates));
                    } else {
                        saveEmployer();
                    }
                },
                error: (req, status, error) => {
                    alert("Error: " + status + " " + error);
                },
                dataType: "json"
            });
        } else {
            saveEmployer();
        }
    }

    function CreateHtmlText(duplicates) {
        var dialogHtmlText = '<p>@Shared.DuplicateEmployerMessage</p>' +
            '<table class="duplicateEmployers" style="width:100%" border="1" cellpadding="2">' +
            '<tr>' +
            '<th>@Employer.name</th>' +
            '<th>@Employer.address1</th>' +
            '<th>@Employer.phone</th>' +
            '<th>@Employer.city</th>' +
            '<th>@Employer.zipcode</th>' +
            '</tr>';
        for (var i = 0; i < duplicates.length; i++) {
            dialogHtmlText += '<tr>' +
                '<td>' +
                duplicates[i]["Name"] +
                '</td>' +
                '<td>' +
                duplicates[i]["Address"] +
                '</td>' +
                '<td>' +
                duplicates[i]["Phone"] +
                '</td>' +
                '<td>' +
                duplicates[i]["City"] +
                '</td>' +
                '<td>' +
                duplicates[i]["ZipCode"] +
                '</td>' +
                '</tr>';
        }

        dialogHtmlText += '</table> <p></p> <p></p>@Shared.SaveMessageDuplicatePersons</p>';

        return dialogHtmlText;
    }

    function saveEmployer() {
        var form = $('#employerCreateForm');
        form.validate();
        form.submit();
        if (form.valid()) {
            setFormData(true);
        }
    }
</script>

Machete.Web/Views/Employer/Edit.cshtml
@using Machete.Web.Helpers
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Localization
@model Machete.Web.ViewModel.Employer

@using Machete.Web.Resources;

@{
    var httpContext = ViewContext.HttpContext;
    var currentCulture = httpContext.Features.Get<IRequestCultureFeature>().RequestCulture.UICulture;
    var currentUrl = UriHelper.BuildRelative(httpContext.Request.PathBase, httpContext.Request.Path, httpContext.Request.QueryString);

    string recType = "employer";
}

@using (Html.BeginForm("Edit", "Employer", FormMethod.Post, 
                        new { @class = "edittab-form EditPost", id="EmployerTab-" + Model.ID }))
{
    @*<input type="button" value="@Employers.viewlink" class="formButton" id="viewEmployer-@Model.ID" />*@
    <input type="button" onclick="FindEmployerDuplicate()" value="@Employers.editsubmit" class="formButton saveBtn"/>
    if (Html.IsInRole("Administrator", "Manager"))
    {
        <input id="deleteEmployerButton-@Model.ID" type="button" value="@Employers.deletesubmit" 
                class="formButton deleteButton" />
    }
    <br />    
    @Html.ValidationSummary(true)
    @Html.EditorForModel()

}
@if (Html.IsInRole("Administrator", "Manager"))
{
    //
    // Only Managers can delete employer records
    // The phonedesk can edit and save
    //
    using (Html.BeginForm("Delete", "Employer", FormMethod.Post, 
                            new { @class = "edittab-form DeletePost", id = "DeleteEmployer-" + Model.ID }))
    {
        @Html.HiddenFor(model => model.ID);
    }
}
@await Html.PartialAsync("WorkOrderIndex", Model)

<div id="duplicatesDialog" title="@Shared.DuplicatePersonsTitle">
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var employerEditForm = $('#EmployerTab-@(Model.ID)');
        $('.formButton').button();
        $('#employerName').focus();
        //
        // machete UI detect changes on forms in tabs
        $("#EmployerTab-@(Model.ID)").mUI('formDetectChanges', {
            recType: "@(recType)",
            formLevel: 1,
            changeConfirm: "@Shared.changeConfirm",
            changeTitle: "@Shared.changeTitle"
            });
        //
        // validation for elements added after page load
        $.validator.unobtrusive.parseDynamicContent($('#EmployerTab-@Model.ID'));
        //
        // delete button confirmation
        $("#deleteEmployerButton-@Model.ID").mUI('formClickDelete', {
            ok: "@Employers.deletesubmit",
            confirm: '@Employers.deleteconfirmation',
            title: '@Employers.deletetitle',
            form: $('#DeleteEmployer-@Model.ID')
        });
        //
        // edit form submit
        $('#EmployerTab-@Model.ID').mUI('tabFormSubmit', {
            create: false,
            selectTab: 0,
            formLevel: 1,
            callback: function () { $('#employerTable').dataTable().fnDraw(); }
        });
    });

    var duplicatesDialog = $("#duplicatesDialog").dialog({
        autoOpen: false,
        height: 400,
        width: 650,
        modal: true,
        closeOnEscape: false,
        buttons: {
            "Cancel": function () { $(this).dialog("close"); },
            "Save": {
                text: "@Employers.editsubmit",
                id: 'duplicateSaveBtn',
                click: function () {
                    $(this).dialog("close");
                    saveEmployer();
                }
            }
        }
    });

    function FindEmployerDuplicate() {

        var form = $('#EmployerTab-@(Model.ID)');
        if (form.valid()) {
            $.ajax({
                url: "/Employer/GetDuplicates",
                data: {
                    name: $('#employer@(Model.ID)-name')[0].value,
                    address: $('#employer@(Model.ID)-address1')[0].value,
                    phone: $('#employer@(Model.ID)-phone')[0].value,
                    city: $('#employer@(Model.ID)-city')[0].value,
                    zipcode: $('#employer@(Model.ID)-zipcode')[0].value
                },
                success: onSuccessFindEmployerDuplicate,
                dataType: "json"
            });
        }
        else {
            saveEmployer();
        }
    }


    function CreateHtmlText(duplicates) {
        var dialogHtmlText = '<p>@Shared.DuplicateEmployerMessage</p>'
            + '<table class="duplicateEmployers" style="width:100%" border="1" cellpadding="2">'
            + '<tr>'
            + '<th>@Employer.name</th>'
            + '<th>@Employer.address1</th>'
            + '<th>@Employer.phone</th>'
            + '<th>@Employer.city</th>'
            + '<th>@Employer.zipcode</th>'
            + '</tr>';
        for (var i = 0; i < duplicates.length; i++) {
            if (duplicates[i].ID == '@Model.ID') { continue; }
            dialogHtmlText += '<tr>'
                + '<td>' + duplicates[i]["Name"] + '</td>'
                + '<td>' + duplicates[i]["Address"] + '</td>'
                + '<td>' + duplicates[i]["Phone"] + '</td>'
                + '<td>' + duplicates[i]["City"] + '</td>'
                + '<td>' + duplicates[i]["ZipCode"] + '</td>'
                + '</tr>';
        }

        dialogHtmlText += '</table> <p></p> <p></p>@Shared.SaveMessageDuplicatePersons</p>';

        return dialogHtmlText;
    }

    function onSuccessFindEmployerDuplicate(result) {
        if (result.duplicates.length > 1) {

            duplicatesDialog.dialog("open");
            duplicatesDialog.html(CreateHtmlText(result.duplicates));
        }
        else {
            saveEmployer();
        }
    }

    function saveEmployer() {
        var form = $('#EmployerTab-@(Model.ID)');
        if (form.valid()) {
            form.submit();
        }
    }
</script>

Machete.Web/Views/Employer/Index.cshtml
@using Machete.Web.Helpers
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Localization

@using Machete.Web.Resources;

@{
    var httpContext = ViewContext.HttpContext;
    var currentCulture = httpContext.Features.Get<IRequestCultureFeature>().RequestCulture.UICulture;
    var currentUrl = UriHelper.BuildRelative(httpContext.Request.PathBase, httpContext.Request.Path, httpContext.Request.QueryString);

    string recType = "employer";
}

<div id="employerTabs" class="ExclusiveTab">
    <ul>
        <li><a href="#employerList" id="employerListTab" class="ListTab">@Employers.listlink</a> </li>

        @if (Html.IsInRole("Administrator", "Manager", "PhoneDesk"))
        {
            <li><a href="/Employer/Create" id="employerCreateTab" class="CreateTab">@Employers.createlink</a></li>
        }
        
    </ul>
    <div id="employerList"> @* This div is the ui.panel  *@
        <input type="button" value="@Machete.Web.Resources.WorkOrders.btnAll" class="formButton" id="allOrdersBtn"/>
        <input type="button" value="@Machete.Web.Resources.WorkOrders.btnOnline" class="formButton" id="onlineOrdersBtn"/>
        <table id="employerTable" class="display">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>LABEL</th>
                    <th>@Employer.active</th>
                    <th>@Employer.name</th>
                    <th>@Employer.address1</th>
                    <th>@Employer.city</th>
                    <th>@Employer.zipcode</th>
                    <th>@Employer.phone</th>
                    <th>@Employer.cellphone</th>
                    <th>@Record.dateupdated</th>
                    <th>@Record.updatedby</th>
                    <th>@Employer.onlineSource</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
<div id="employerSelectDialog" title="@WorkOrders.empChgConfirmTitle">
    <table id="employerSelectTable" class="display">
        <thead>
            <tr>
                <th>ID</th>
                <th>LABEL</th>
                <th>@Machete.Web.Resources.Employer.active</th>
                <th>@Machete.Web.Resources.Employer.name</th>
                <th>@Machete.Web.Resources.Employer.address1</th>
                <th>@Machete.Web.Resources.Employer.city</th>
                <th>@Machete.Web.Resources.Employer.zipcode</th>
                <th>@Machete.Web.Resources.Employer.phone</th>
                <th>@Machete.Web.Resources.Employer.cellphone</th>
                <th>@Machete.Web.Resources.Record.dateupdated</th>
                <th>@Machete.Web.Resources.Record.updatedby</th>
            </tr>
        </thead>
    </table>
</div>
@await Html.PartialAsync("WorkerIndex")
<script type="text/javascript">
    $(document).ready(function () {
        $('.formButton').button();
        ////////////////////////////////////////////////////////////////
        //
        // Create Employer table
        //
        var oTable = jqrfyTable({
            table: $('#employerTable'),
            tab: $('#employerTabs'),
            options: {
                //"sScrollY": "315px",
                //"iDisplaylength": 15,
                "bPaginate": true,
                "bLengthChange": true,
                "aaSorting": [[9, 'desc']],
                "bFilter": true,
                "bSort": true,
                "bInfo": true,
                "bAutoWidth": false,
                "bServerSide": true,
                "sAjaxSource": "/Employer/AjaxHandler",
                "bProcessing": true,
                "oLanguage": datatable_lang_@(currentCulture.TwoLetterISOLanguageName),
                "aoColumns": [                           //dataTable column definition
                                {"mDataProp": "tabref",  "bSearchable": false, "bSortable": false, "bVisible": false },
                                {"mDataProp": "tablabel",  "bSearchable": false, "bSortable": false, "bVisible": false },
                                {"mDataProp": "active" },
                                {"mDataProp": "name" },
                                {"mDataProp": "address1" },
                                { "mDataProp": "city" },
                                { "mDataProp": "zipcode" },
                                { "mDataProp": "phone" },
                                { "mDataProp": "cellphone" },
                                {"mDataProp": "dateupdated" },
                                { "mDataProp": "updatedby", "bSortable": false },
                                { "mDataProp": "onlineSource", "bSearchable": false, "bSortable": true, "bVisible": true }
                            ]
            },
            dblClickEvent: null,
            tabLabel: "@(recType)"
        });
        $('#employerTabs').mUI('createTabs', {
            prefix: "ui-tabs-employer-",
            formLevel: 1,
            changeConfirm: "@(Machete.Web.Resources.Shared.changeConfirmPerson)",
            changeTitle: "@(Machete.Web.Resources.Shared.changeTitlePerson)",
            updateDataTable: true
            });
        $('#allOrdersBtn').click(function() {
            oTable.dataTable().fnResetAllFilters();
        });
        $('#onlineOrdersBtn').click(function() {
            oTable.dataTable().fnResetAllFilters(false);
            oTable.dataTable().fnFilter(true, 9); //sync with DT array above
        });

        $('#employerCreateTab').click(function () {

            // capturing not-saved typed fields from Create New Employer form to localStorage variables

            // serializeArray captures all the form fields
            var employerFormContent = $('#employerCreateForm').serializeArray();
            window.localStorage.setItem("employerCreateForm", JSON.stringify(employerFormContent));
        });
        ////////////////////////////////////////////////////////////////
        //
        // table for selecting employer (for workorder move functionality)
        //
        $('#employerSelectTable').dataTable().fnDestroy();
        $('#employerSelectTable').dataTable({
            "bPaginate": true,
            "bDeferLoading": true,
            "bLengthChange": true,
            "aaSorting": [[7, 'desc']],
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "iDeferLoading": true,
            "bAutoWidth": false,
            "bServerSide": true,
            "sAjaxSource": "/Employer/AjaxHandler",
            "oLanguage": datatable_lang_@(currentCulture.TwoLetterISOLanguageName),
            "bProcessing": true,
            "aoColumns": [
                            {"mDataProp": "tabref",  "bSearchable": false, "bSortable": false, "bVisible": false },
                            {"mDataProp": "tablabel",  "bSearchable": false, "bSortable": false, "bVisible": false },
                            {"mDataProp": "active" },
                            {"mDataProp": "name" },
                            {"mDataProp": "address1" },
                            { "mDataProp": "city" },
                            { "mDataProp": "zipcode" },
                            { "mDataProp": "phone" },
                            { "mDataProp": "cellphone" },
                            {"mDataProp": "dateupdated" },
                            {"mDataProp": "updatedby", "bSortable": false }
            ],
            // callback populates html attr with row data from JSON
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                $(nRow).attr('recordid', aData['EID']);
                return nRow;
            }
        }).fnSetFilteringDelay(250);
        $('#employerSelectTable_filter input').attr('ID', 'employerSelectTable_searchbox');
        //////////////////////////////////////////////////
        //
        //

        $('#employerSelectTable').find('tbody').mUI('selectEmployerDblClick',
        {
            okButton: "@WorkOrders.empChgConfirmSubmit",
            message: "@WorkOrders.empChgConfirm",
            title: '@WorkOrders.empChgConfirmSubmit'
        });
        $('#employerSelectDialog').hide();
        $('#employerSelectTable').hide()
        return true;
    });
</script>